server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
        - id: iliopoulos
          uri: http://172.31.0.221:8080
          predicates:
            - Host=iliopoulos-nikolas.xyz
        - id: seasidehouseinneamakri
          uri: http://172.31.0.221:8081
          predicates:
            - Host=iliopoulosrent.com, seasidehouseinneamakri.com
