server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
        - id: iliopoulos
          uri: http://localhost:8080
          predicates:
            - Host=iliopoulos-nikolas.xyz
        - id: seasidehouseinneamakri
          uri: http://localhost:8081
          predicates:
            - Host=seasidehouseinneamakri.com