server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
        - id: iliopoulos
          uri: http://127.0.0.1:8080
          predicates:
            - Host=iliopoulos-nikolas.xyz
        - id: seasidehouseinneamakri
          uri: http://127.0.0.1:8081
          predicates:
            - Host=seasidehouseinneamakri.com